-- ============================================================
-- PRIVATE SOURCES BUCKET — AL-Azher IT Hub (2026-09-05)
-- Source files (some copyrighted textbooks) must only be
-- reachable by signed-in students through short-lived signed
-- URLs generated by the app. This closes:
--   1. direct public downloads  (/object/public/sources/...)
--   2. anonymous bucket listing (object/list/sources)
--   3. anonymous signed-URL minting (object/sign/sources)
-- Idempotent; safe to re-run.
-- Apply ONLY AFTER the signed-URL code is deployed (the app
-- falls back gracefully until then, but public URLs die the
-- moment the bucket goes private).
-- ============================================================

-- 1) Flip the bucket to private
update storage.buckets
   set public = false
 where id = 'sources';

-- 2) Replace the open read policy with an authenticated-only one
--    (SELECT on storage.objects governs download + list + sign)
drop policy if exists "sources_public_read" on storage.objects;
drop policy if exists "sources_public_download" on storage.objects;
drop policy if exists "sources_read" on storage.objects;

create policy "sources_auth_read" on storage.objects
  for select using (
    bucket_id = 'sources'
    and auth.role() = 'authenticated'
  );

-- Admin upload/delete/update policies are unchanged (admin-only)
-- and were pinned by migration-supabase-storage.sql +
-- migration-security-hardening.sql. Re-assert upload here so the
-- intent survives any policy-name drift:
drop policy if exists "sources_auth_upload" on storage.objects;
drop policy if exists "sources_admin_upload" on storage.objects;
create policy "sources_admin_upload" on storage.objects
  for insert with check (
    bucket_id = 'sources'
    and public.is_current_user_admin()
    and public.is_safe_source_object(name, coalesce(metadata->>'mimetype', ''))
  );

-- ============================================================
-- VERIFICATION (anon must fail everywhere, authed must pass)
-- ============================================================
-- set local role anon;
-- select * from storage.objects where bucket_id = 'sources';   -- must return 0 rows
-- reset role;
-- select count(*) from storage.objects where bucket_id = 'sources'; -- as postgres
